### PR TITLE
Support multi-targeting via a single project

### PR DESCRIPTION
**Pull request by drewnoakes**
Use single project to target .NET Framework & Core. SDK-style projects allow multi-targeting which makes this much simpler.

The AsysTech.CredentialManager project will also pack a single package that targets multiple frameworks

Also made `CredentialExtensions` public as the README suggests its extension method is supposed to be public.

### CODE REVIEW

**Comment by drewnoakes** [comment]
This PR is intended to support the Git Extensions project's conversion to .NET Core 3:

https://github.com/gitextensions/gitextensions/pull/7162

If merged, please bump the version and publish a new package on nuget.org. I suggest delisting the ".Core" version as it's not needed.

Any questions, I'm happy to help.

**Comment by mvadu** [comment]
Thank you @drewnoakes and @RussKie for this PR. I was new to netstandard when I ported, and thought it needs to be in different package. Thank you!

**Comment by mvadu** [comment]
@drewnoakes after merging this I am trying to open the solution in Visual Studio 2019 (Community edition), and its complaining about 'Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1702	ProjectReference 'C:\Users\adyst\source\repos\AdysTech\CredentialManager\src\AdysTech.CredentialManager\AdysTech.CredentialManager.csproj' was resolved using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This project may not be fully compatible with your project.	CredentialManager.Test	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1655`	

Can this error be ignored?

**Comment by drewnoakes** [comment]
@mvadu you're welcome.

Regarding the warning, I assume that warning's coming from the test project, so it won't effect the generated package. I'll try and investigate over the next couple of days.

**Comment by drewnoakes** [comment]
@mvadu I haven't had time to look into this. Given it's only a reference from the test project and the tests ran for all targets, I don't think there's an actual problem here.

**Comment by mvadu** [comment]
@drewnoakes thank you.. I just realized that with your PR the published NugetPakage name got changed too. Since I am also deprecating previous core only package, I have reverted that change, Also with this PR the project was unsigned (i.e. not using strong name) and I have fixed it with #43. You should be able to consume v2.1.1 on Nuget Package now. https://www.nuget.org/packages/AdysTech.CredentialManager/

**Pull request merged**
