### PR TITLE
Add CredentialType as an extra optional parameter when saving credentials

### PR DESCRIPTION
**Pull request by esrahofstede**
Add CredentialType as an extra optional parameter when saving credentials so when can store Windows credentials, Generic credentials  and Certificates instead of just Generic credentials

### CODE REVIEW

**Comment by mvadu** [comment]
Have you tried testing it? Saving is doable, but the problem comes with the reading part. Let me know if the read part works as well for the non generic credentials.

**Comment by cwchapma** [comment]
I have successfully read Windows type credentials - at least the username and domain, the password is blank but that is by design (for security).  However, writing Windows type credentials is useful for for setting up authentication to something like SQL server using windows credentials different than the current user.  Even if it's impossible to read the password using the library, the password is still propagated to SQL server.

**Comment by mvadu** [comment]
@cwchapma I assume you have tested this PR based build? The PR is not actually changing the underlying store logic, its just changing the type (if passed in as a non generic credential). Retrieve logic is what prevented me from implementing it in the past. If you have tested that password gets passed through the library (not sure how) then I am ready to merge this PR so other folks can give it a shot.

**Comment by cwchapma** [comment]
I hadn't tested but I have now and I can confirm it does allow me to save Windows type credentials and setup authentication for SQL server.

**Pull request merged**
